Add fixes related to optinal fields and those without validation function
debtcollective/discourse-debtcollective-signup-fields pull request #1
Opened 2019-01-05 12:23 UTC by duranmla

Closes https://github.com/debtcollective/parent/issues/268

_Fixes:_
- Use Ember.set to set custom options preventing fatal error on edge cases, Avoid to break built-in dropdowns
- Prevent to run validations for empty value fields, set default validation function to return true

![http://recordit.co/7qj6dMaYYn](http://recordit.co/7qj6dMaYYn.gif)

2019-01-05 21:54 UTC, orlando commented
@duranmla leaving the input empty when is not required shouldn't render the error state (Phone number field becoming red)

2019-01-05 21:55 UTC, orlando requested changes
Fields shouldn't be in error state when they are empty and are not required

2019-01-07 09:55 UTC, duranmla commented
But is because the format is not valid (is empty), would you still want to remove the color from that case? By doing so, we won't be showing feedback that your format is not valid and when the user tries to add values it won't know if it is failing or not. **Perhaps we can show the error if you fill some data and prevent to submit if the data you are trying to submit is not the right one.**

2019-01-07 10:23 UTC, orlando commented
Yes, we don’t need the feedback because in non required fields it should show only when you have data.

Enviado desde mi iPhone

El 7 ene 2019, a la(s) 3:55, Alexis Duran <notifications@github.com> escribió:

> But is because the format is not valid (is empty), would you still want to remove the color from that case? By doing so, we won't be showing feedback that your format is not valid and when the user tries to add values it won't know if it is failing or not. Perhaps we can show the error if you fill some data and prevent to submit if the data you are trying to submit is not the right one.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.

2019-01-07 19:52 UTC, duranmla commented
@orlando PR is now fixed, please let me know.

2019-01-10 21:46 UTC, orlando approved these changes

2019-01-10 21:46 UTC, orlando commented
@duranmla LGTM

2019-01-10 21:46 UTC, merged